# Generated by Django 2.1.1 on 2018-10-12 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('to_email', models.EmailField(max_length=100)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField(max_length=500)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='sender',
        ),
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
