# Generated by Django 2.1.1 on 2018-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
